model_config:
zoo_name: 'get_torchvision_model'
zoo_args:
  model_config:
    name: 'resnet18'
    params:
      pretrained: True
  #    num_classes: 10


logging_config:
wandb_config:
project_name: 'testproject'
entity: 'rezafuru'
run_name: 'testrun'
enabled: False
local_logging_config:
config_path: 'config/example_config.yaml'

BaseExperimentConfig:
  device: 'cpu'
  test_only: False
datasets:
params:
  cifar10:
    name: &dataset_name 'cifar10'
    type: 'CIFAR10'
    #    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    root: &root_dir './resources/dataset/cifar10'
    splits:
      train:
        #        dataset_id: &cifar10_train !join [*dataset_name, '/train']
        dataset_id: &cifar10_train 'cifar10/train'
        params:
          root: *root_dir
          train: True
          download: True
          transform_params:
            - type: 'RandomCrop'
              params:
                size: 32
                padding: 4
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [ 0.49139968, 0.48215841, 0.44653091 ]
                std: [ 0.24703223, 0.24348513, 0.26158784 ]
      val:
        #        dataset_id: &cifar10_val !join [*dataset_name, '/val']
        dataset_id: &cifar10_val 'cifar10/val'
        params:
          root: *root_dir
          train: False
          download: True
          transform_params: &val_transform
            - type: 'ToTensor'
              params:
            - *normalize
      test:
        #        dataset_id: &cifar10_test !join [*dataset_name, '/test']
        dataset_id: &cifar10_test 'cifar10/test'
        params:
          root: *root_dir
          train: False
          download: True
          transform_params: *val_transform

aggregator_config:
trainer_base_config:
train_config:
train_dataset_id: *cifar10_train
epochs: 5
train_loader_params:
  batch_size: 32
  num_workers: 0
  shuffle: True
  pin_memory: True
optimizer:
  type: 'SGD'
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
criterion:
  type: 'CrossEntropyLoss'
  params:
    reduction: 'mean'
validation_config:
main_metric: 'Accuracy'
eval_dataset_id: *cifar10_val
eval_loader_params:
  batch_size: 32
  num_workers: 0
  shuffle: False
  pin_memory: True
eval_metrics: ['Accuracy']
client_type: 'TorchClient'
client_config:
#client_kwargs:
server_type: 'TorchServer'
number_clients: &num_clients 2
server_config:
server_address: '127.0.0.1:5050'
rounds: 2


central_test_config:
central_eval_metrics: [ 'Accuracy' ]
central_dataset_id: *cifar10_test
central_loader_params:
  batch_size: 32
  num_workers: 0
  shuffle: False
  pin_memory: True

strategy_config:
min_available_clients: *num_clients
min_fit_clients: *num_clients
min_evaluate_clients: *num_clients




